---
apiVersion: v1
kind: Pod
metadata:
  name: csicephfs-demo-pod
  annotations: 
   "helm.sh/hook": post-install 
   "helm.sh/hook-weight": "7"
spec:
  containers:
    - name: web-server
      image: nginx
      volumeMounts:
        - name: mypvc
          mountPath: /var/lib/www/html
  volumes:
    - name: mypvc
      persistentVolumeClaim:
        claimName: cephfs-pvc
        readOnly: false
