---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cephfs-pvc
  annotations: 
   "helm.sh/hook": post-install 
   "helm.sh/hook-weight": "6"
  labels:
    group: snapshot-test
    
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ceph-filesystem
