---
apiVersion: v1
kind: Pod
metadata:
  name: csirbd-block-demo-pod
  annotations: 
   "helm.sh/hook": post-install 
   "helm.sh/hook-weight": "9"
spec:
  containers:
    - name: centos
      image: quay.io/centos/centos:latest
      command: ["/bin/sleep", "infinity"]
      volumeDevices:
        - name: mypvc
          devicePath: /dev/xvda
  volumes:
    - name: mypvc
      persistentVolumeClaim:
        claimName: raw-block-rbd-pvc
