---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: raw-block-rbd-pvc
  annotations: 
   "helm.sh/hook": post-install 
   "helm.sh/hook-weight": "8"
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-ceph-block
